### ISSUE TITLE
feature request: block generation

### ISSUE THREAD

**Issue by reticivis-net** [fzzyhmstrs/EMI_loot#10]
something like Roughly/Just Enough Resources that shows in what dimension and at what level a certain block generates
![image](https://user-images.githubusercontent.com/35177464/215017099-a66edeae-abea-434d-b814-6afdba2f8e47.png)
https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources

**Comment by fzzyhmstrs** [comment]
I am aware of RER,, and this functionality is already on the todo list! :)
![image](https://user-images.githubusercontent.com/72876796/215101609-2f358199-c008-48f0-8d8a-bb41c71e4a39.png)

**Comment by fzzyhmstrs** [comment]
I can finally close this! This is now provided by EMI Ores!
* [https://www.curseforge.com/minecraft/mc-mods/emi-ores](https://www.curseforge.com/minecraft/mc-mods/emi-ores)
* [https://modrinth.com/mod/emi-ores](https://modrinth.com/mod/emi-ores)
