### ISSUE TITLE
add enchantment table

### ISSUE THREAD

**Issue by HexCodeFFF** [fzzyhmstrs/EMI_loot#11]
Not sure if this is better for this mod or EMI itself but having an in-game way to view if an enchant can be obtained via table and if so at what XP level would be really useful

**Comment by fzzyhmstrs** [comment]
My inclination would be to say this doesn't fit into EMI Loot. EMI Loot provides information on objects with loot tables primarily.

Enchanting Table results are all hardcoded, and there exists the underlying issue of having to deal with the multiple popular mods that change how this works, or that add completely new enchanting tables that provide different results (Like the Imbuing Table in my mod Amethyst Imbuement). I'm not sure where this would best be put, to be honest, or how it would be done.
