### ISSUE TITLE
Add Enchantment Description compat

### ISSUE THREAD

**Issue by teleheel** [fzzyhmstrs/EMI_loot#13]
With the Enchantment Descriptions mod the tooltip contains the description `enchantment.emi_loot.random.desc`. Would be nice if this could be changed to a more generic description, such as "Generic enchanted book." or something.

Screenshot:
![image](https://user-images.githubusercontent.com/97514922/218703216-7dde76c4-a82c-4b6e-abf7-7e8c14a7f998.png)

**Comment by fzzyhmstrs** [comment]
Thanks for the heads up; I can add this in the next version.

**Comment by fzzyhmstrs** [comment]
added in 0.6.1
