### ISSUE TITLE
[Bug] Unable to Load or Create Worlds

### ISSUE THREAD

**Issue by greensad** [fzzyhmstrs/EMI_loot#14]
When trying to create or load a world I get the error:

Connection Lost
Internal Exception:
I_iava.lang.5tringIndexüutüf60undsException:
offset 16.51 count 128791 length 4239

Loads fine before adding the mod or after removing it.

Log: https://mclo.gs/lrmk6J3

**Comment by fzzyhmstrs** [comment]
Interesting... something is providing EMI Loot with an excess of loot condition data, more than a network packet can send. At least that's what appears to be happening..

Can you please run EMI Loot in Debug mode? The option to enable that is found in the config json `EmiLootConfig_v[x].json`, and is the `debugMode` option. It will still crash, but EMI Loot will barf out a lot more log information that might help me track down the source of the issue.

**Comment by greensad** [comment]
Ah okay, I'll try that out now!

**Comment by greensad** [comment]
https://mclo.gs/SxUtJL7

**Comment by fzzyhmstrs** [comment]
Hrmm, close, but mclo.gs cuts the log off at 25000 lines apparently. Or the log cutoff at 25000 lines... Can you paste the actual log file in here? It might need to be zipped.

**Comment by greensad** [comment]
Sorry about that, I knew better too: https://paste.ee/p/EX6pJ

**Comment by fzzyhmstrs** [comment]
This was fixed I believe when I updated my networking related to another issue
