### ISSUE TITLE
Mob icons displays incorrectly

### ISSUE THREAD

**Issue by Disketaa** [fzzyhmstrs/EMI_loot#27]
All the mobs was stucked in the top left corner of the screen. I'm using Custom Entity Models and Fresh Animations, maybe they re conflicting

![image](https://github.com/fzzyhmstrs/EMI_loot/assets/76956762/101c06ff-8a7e-4249-8f7b-21ea74ee024b)

**Comment by fzzyhmstrs** [comment]
Thank you for the report. I noticed in new EMI versions the mobs were missing but didn't notice them piled into the corner like this. This gives me something to work with for making a fix.

**Comment by fzzyhmstrs** [comment]
Fixed this in EL 0.6.5
