### ISSUE TITLE
Icons SUGGESTION

### ISSUE THREAD

**Issue by Disketaa** [fzzyhmstrs/EMI_loot#28]
Would be nice if all icons were compacted and written as a text in tooltip when hovering an item. I attach the reference, looks more clear and little messy for me

![image](https://github.com/fzzyhmstrs/EMI_loot/assets/76956762/4f771274-9795-467f-9f75-a6168ed77121)

**Comment by fzzyhmstrs** [comment]
Thank you for the suggestion. Please know that EMI Loot is a side project for me, and I just finished a solid week of work porting 11 mods to the newer versions, so if I take any action on this, it won't be for a while.

**Comment by fzzyhmstrs** [comment]
over a year later, and I am implementing this in the soon-to-be-released new versions
