### ISSUE TITLE
Round chances

### ISSUE THREAD

**Issue by Disketaa** [fzzyhmstrs/EMI_loot#29]
Would be also nice to see a config or something to round all the chance values, cause in my opinion it's not necessary like that
![image](https://github.com/fzzyhmstrs/EMI_loot/assets/76956762/9d005dbc-9b35-4f35-960a-f68bb2167e34)

**Comment by fzzyhmstrs** [comment]
I'll take a look into this at some point, because I actually already do have a rounding feature for most of the numbers displayed. Seems something missed here.

**Comment by fzzyhmstrs** [comment]
Fixed in EL 0.6.5
