### ISSUE TITLE
[1.19.2] Incompatible with Requiem, throws datapack error on world load with both enabled.

### ISSUE THREAD

**Issue by grimSagely** [fzzyhmstrs/EMI_loot#3]
[latest.log](https://github.com/fzzyhmstrs/EMI_loot/files/9688206/latest.log)

**Comment by fzzyhmstrs** [comment]
Thank you for the report. I will look into it!

**Comment by fzzyhmstrs** [comment]
This has been fixed for a hot minute now. Never closed the issue; oops!
