### ISSUE TITLE
Issue with Cavernous datapack [1.20.1]

### ISSUE THREAD

**Issue by scyleaf** [fzzyhmstrs/EMI_loot#33]
EMI loot issue with Cavernous- 'Data pack validation failed'
<pre>
Base:
 * Minecraft 1.20.1
 * Quilt loader 0.19.2-beta.4

Loaded mods:
 * EMI 1.0.5+1.20.1+fabric
 * EMI Loot 0.6.4+1.20.1
 * Quilted Fabric API 7.0.4+0.84.0-1.20.1

Datapacks:
 * cavernous-r-v0-0
</pre>

Relevant logs: https://paste.ee/p/eX8SC

**Comment by fzzyhmstrs** [comment]
There seems to be a strange issue with the datapack, where they have a LootCondition in place of a LootTable. I would raise an issue with them and see what they might know:

`java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.loot.condition.AnyOfLootCondition cannot be cast to class net.minecraft.loot.LootTable (net.minecraft.loot.condition.AnyOfLootCondition and net.minecraft.loot.LootTable are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @239963d8)`

**Comment by fzzyhmstrs** [comment]
Ah, I see. This is because predicates and modifiers can be put into the loot_tables folder. This is on me to resolve

**Comment by fzzyhmstrs** [comment]
Fixe in 0.6.4.1, tested with `cavernous-r-v0-2` in-game
