### ISSUE TITLE
Issue with Frostiful mod [1.20.1]

### ISSUE THREAD

**Issue by scyleaf** [fzzyhmstrs/EMI_loot#35]
EMI Loot issue with the Frostiful mod. Crashes on preparing for world creation.

<pre>
Base:
 * Minecraft 1.20.1
 * Quilt loader 0.19.2

Loaded mods:
 * EMI 1.0.10+1.20.1+fabric
 * EMI Loot 0.6.4+1.20.1
 * Quilted Fabric API 7.0.6+0.85.0-1.20.1
 * Frostiful 0.7.1
 * Thermoo 1.6.1
 * Cloth Config v11 11.1.106
</pre>

Relevant logs: https://paste.ee/p/Au1gK

**Comment by fzzyhmstrs** [comment]
Seems like I missed the quilt tag on that version. tagged now

**Comment by scyleaf** [comment]
Yeah, apologies! I use ferium, and it seems it didn't want to upgrade because of the missing Quilt tag. Tested and works correctly on version 0.6.4.1. :) thanks
