### ISSUE TITLE
[1.20.1] [bug] Incorrect Percentages

### ISSUE THREAD

**Issue by N0aW** [fzzyhmstrs/EMI_loot#36]
The Netherite Upgrade Template says that there's a 100% chance of getting one from any bastion chest.

In reality, only one chest has this 100% chance, and the other 3 only have a 10% chance.

This might affect other items as well.

**Comment by fzzyhmstrs** [comment]
Thanks for the report. I'll take a look into it as soon as I'm able, which may be a bit as I have quite a busy schedule rn.

**Comment by fzzyhmstrs** [comment]
resolved quite a while ago, forgot to close this
