### ISSUE TITLE
Long chest loot table names cant be viewed properly.

### ISSUE THREAD

**Issue by Mahadbaloch** [fzzyhmstrs/EMI_loot#38]
Loot tables in chests like from repurposed structures chests are impossible to view for me. When I view them the name gets cut off with ...   

Is there a solution already or is this a bug

**Comment by fzzyhmstrs** [comment]
This was never a bug, the loot table name was too long to fit into the title. Soon-to-be-released version adds a tooltip to show the entire name when hovered.
