### ISSUE TITLE
Support for Forge 1.19.2?

### ISSUE THREAD

**Issue by ColonelGerdauf** [fzzyhmstrs/EMI_loot#39]
This version remains somewhat popular today, due to the uncertainty about 1.20.x.

**Comment by unilock** [comment]
Unfortunately, given EMI Loot does not support Forge at all, I doubt there will be a release for an older version of the modloader.

...officially! I ported EMI Loot to Forge 1.19.2 a few months ago, and it even mostly works! Here's my fork (you will have to build it yourself): https://github.com/unilock/EMI_loot

Note that I never actually used it, so there is the definite possibility that it will break catastrophically. If you run into any issues, feel free to open an issue on that repository's issue tracker - but not here, please.

**Comment by unilock** [comment]
My fork has now been published on CurseForge and Modrinth, so this issue can be closed :)

**Comment by fzzyhmstrs** [comment]
closing (finally)
