### ISSUE TITLE
Item with "random enchantment" obtained from ruined portal chest

### ISSUE THREAD

**Issue by MeeniMc** [fzzyhmstrs/EMI_loot#4]
I looted a ruined portal chest, and got the following item from it. 

```[20:17:39] [Render thread/INFO]: [System] [CHAT] MeeniMe has the following entity data: {Slot: 5b, id: "minecraft:golden_leggings", tag: {Damage: 0, Enchantments: [{id: "emi_loot:random", lvl: 1s}], RepairCost: 1}, Count: 1b}```

I had the following mods when that happened (not many as you see) 

  [✔] CITResewn-1.1.2+1.19.2
  [✔] continuity-2.0.1+1.19
  [✔] DistantHorizons-1.6.9a-1.19.2
  [✔] emi_loot-0.1.0+1.19
  [✔] emi-0.4.0+1.19
  [✔] EMITrades-fabric-1.0.2+mc1.19.2
  [✔] fabric-api-0.62.0+1.19.2
  [✔] fabric-carpet-1.19.1-1.4.83+v220727
  [✔] highspeed-rail-0.0.1
  [✔] indium-1.0.9+mc1.19.2
  [✔] itemscroller-fabric-1.19.2-0.17.1
  [✔] litematica-fabric-1.19.2-0.12.5
  [✔] lithium-fabric-mc1.19.2-0.9.1
  [✔] malilib-fabric-1.19.2-0.13.0
  [✔] modmenu-4.0.6
  [✔] quickarmorswap-1.0.0
  [✔] reeses_sodium_options-1.4.7+mc1.19.2-build.59
  [✔] servercore-1.3.2-1.19.2 (1)
  [✔] sodium-extra-0.4.11+mc1.19.2-build.68
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] starlight-1.1.1+fabric.ae22326

**Comment by fzzyhmstrs** [comment]
This should be resolved in EMILoot 0.2.0.That was meant as a tooltip placeholder, forgot to exclude it from actual selection...
