### ISSUE TITLE
use the `emi_loot` namespace instead of the `emi` namespace in recipe id

### ISSUE THREAD

**Issue by walksanatora** [fzzyhmstrs/EMI_loot#47]
another nitpick since I am currently dumping recipes for future EMC usage.
please don't use the emi namespace. it makes it a lot harder to notice which recipes are yours.
as inorder to check if it is your recipe I have to check for `emi` namespace and then `emi_loot` as the "root" folder of the path
instead of `emi:emi_loot/block_drops/minecraft/blocks/oak_leaves` it could instead be `emi_loot:block_drops/minecraft/blocks/oak_leaves`  this also makes more sense as the recipe category is `emi_loot:block_drops`

**Comment by fzzyhmstrs** [comment]
Those recipe ids are synthetic and were made when Emi's recommendation was to use the emi namespace for them. I'll put a not to update them now that her recommendation has changed

**Comment by walksanatora** [comment]
idk if the reccomendation has changed.
It is just that it doesen't feel quite right to put it under emi namespaces. but I can re-check if it is still correct (and afterall I can still filder by recipe category)

**Comment by walksanatora** [comment]
![image](https://github.com/fzzyhmstrs/EMI_loot/assets/47339836/1afc3115-313c-43da-9002-9424f562551f)
confirmed by emi. it was propper form. but is now outdated

**Comment by fzzyhmstrs** [comment]
this has been fixed for a while, forgot to close.
