### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by KIRUYXAN** [fzzyhmstrs/EMI_loot#54]
Why install this mod on the server for it to work on the server?

**Comment by fzzyhmstrs** [comment]
Because loot tables are server-side.

**Comment by KIRUYXAN** [comment]
As for me, this thing works like a regular wiki and should not require a server

**Comment by KIRUYXAN** [comment]
And Just Enough Resources, which is similar in operation, produces approximately the same information without requiring the server side
