### ISSUE TITLE
Option to remove categories / recipes

### ISSUE THREAD

**Issue by QwertRvg** [fzzyhmstrs/EMI_loot#59]
A lot of Block Drop recipes are wrong / very weird / not well understandable. A config file to disable these would be great!

**Comment by fzzyhmstrs** [comment]
This is possible with resource pack formats built into EMI: [https://github.com/emilyploszaj/emi/wiki/Recipe-Filters](https://github.com/emilyploszaj/emi/wiki/Recipe-Filters)
