### ISSUE TITLE
Sending packets to unsupported clients

### ISSUE THREAD

**Issue by Linguardium** [fzzyhmstrs/EMI_loot#60]
https://github.com/fzzyhmstrs/EMI_loot/blob/88d0682d4d4595d0752f16831ec6367e5bb68178/src/main/java/fzzyhmstrs/emi_loot/parser/LootTableParser.java#L68-L88

Best to run a canSend here before sending so that you dont end up sending data to clients that dont support your mod

**Comment by fzzyhmstrs** [comment]
fixed, forgot to close
