### ISSUE TITLE
EMI Loot v0.6.6 - 1.20.1 Forge Issue

### ISSUE THREAD

**Issue by M0nkeyPr0grammer** [fzzyhmstrs/EMI_loot#63]
After updating this mod from v0.6.5 the /reload command no longer works and produces these [logs](https://mclo.gs/CVQVwbR). I have down-graded to the previous version and /reload command works without issues.

**Comment by MundM2007** [comment]
Also happens for me, also it can only be reproduced with emi loot and it's dependencies. This is the log in that case
[latest.log](https://github.com/user-attachments/files/15853497/latest.log)

**Comment by unilock** [comment]
Please try the [latest version](https://modrinth.com/mod/emi-loot/version/0.6.6+fix1+1.20.1+forge) of EMI Loot for Forge ("0.6.6+fix1"). If that doesn't work, please report back.

**Comment by MundM2007** [comment]
still happens, with only lootjs
[latest.log](https://github.com/user-attachments/files/15937980/latest.log)
I've tested with the newest version on curseforge

**Comment by unilock** [comment]
@MundM2007 This version has it fixed: https://www.curseforge.com/minecraft/mc-mods/emi-loot/files/5458725

**Comment by MundM2007** [comment]
It works now thanks!

**Comment by M0nkeyPr0grammer** [comment]
I can confirm it also works for me, thanks for the fix!

**Comment by fzzyhmstrs** [comment]
Closing as fixed
