### ISSUE TITLE
Full Text cut off for some structures

### ISSUE THREAD

**Issue by Tubnuts** [fzzyhmstrs/EMI_loot#64]
For some structures with longer text, it cuts off and is unavailable to be seen. For example, for loot chests in the structures of the Repurposed Structuers mod, the text says Repurposed Structures L.... 

![image](https://github.com/fzzyhmstrs/EMI_loot/assets/172697849/7a71a048-ba52-4f1d-bc54-fd92bbc466b1)

**Comment by fzzyhmstrs** [comment]
Soon-to-be-released version adds a tooltip to show the entire name when hovered.
