### ISSUE TITLE
[1.19.2] New 0.6.6 version causes Crash when launching game

### ISSUE THREAD

**Issue by ffuentesm** [fzzyhmstrs/EMI_loot#65]
emi_loot-0.6.6+fix1+1.19.2+forge
The new mod version causes the game to crash on launch. 

[crash-2024-06-21_18.15.51-client.txt](https://github.com/user-attachments/files/15934216/crash-2024-06-21_18.15.51-client.txt)

**Comment by fzzyhmstrs** [comment]
@unilock can you take a look please

**Comment by unilock** [comment]
Builds that should fix this issue:  
[1.19.2](https://github.com/unilock/EMI_loot/actions/runs/9625438733)  
[1.20](https://github.com/unilock/EMI_loot/actions/runs/9625428761)

God damn Forge :/

**Comment by fzzyhmstrs** [comment]
-fix2- is out on CF and Modrinth
