### ISSUE TITLE
incorect percentages displayed for mob drops

### ISSUE THREAD

**Issue by thiccmeme** [fzzyhmstrs/EMI_loot#67]
![2024-07-04_22 51 59](https://github.com/fzzyhmstrs/EMI_loot/assets/79066376/58470149-88b7-4436-9751-fd05b7d695ba)
![2024-07-04_22 52 06](https://github.com/fzzyhmstrs/EMI_loot/assets/79066376/bfcd6de6-feac-4408-ab28-1e10448e0cac)
![2024-07-04_22 52 12](https://github.com/fzzyhmstrs/EMI_loot/assets/79066376/d532f9f4-4e3b-41c9-9cad-70c994eef61e)

Wither skeleton, endermen. and cows just to name a few are all displaying 100% drop chances for wither skulls. ender pearls. and leather respectively. 

This affects many more mob drops as well. these are just three examples.

I am running version 0.6.6 fix 3 on forge 1.20.1 47.3.0

**Comment by fzzyhmstrs** [comment]
The "?" or other icons next to the items will show the drop percentage modifier. That is it's chance to drop in the pool (100% because it's the only item there). I know that's a bit confusing, so I am plotting and scheming on a bit of a rework
