### ISSUE TITLE
[Issue] When running the mod within a server EMI Loot tabs do not appear in EMI 

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [fzzyhmstrs/EMI_loot#68]
# EMI Loot doesn't appear on servers

When the mod is used in either both within the server and client or only client, joining a server and attempting to fetch EMI loot recipes will result in nothing

## Workaround

Currently i was able to get the mod to work sometimes within a server if the user first opens a single player world

## Additional Information

EMI Loot version: `emi_loot-0.6.6+fix3+1.20.1+forge.jar`
EMI version: `emi-1.1.10+1.20.1+forge.jar`
Bad Packets version: `badpackets-forge-0.4.3.jar`
Server Type: `forge/1.20.1-47.3.0/unix`
Tested on: Windows 10, 11, and Linux

**Comment by fzzyhmstrs** [comment]
@unilock related to the 1.19.2 fix you handled recently?

**Comment by unilock** [comment]
:(

**Comment by unilock** [comment]
This build should have it fixed: https://github.com/unilock/EMI_loot/actions/runs/9857410001

I could have sworn it was already working though... grrr.

**Comment by fzzyhmstrs** [comment]
Closing as fixed
