### ISSUE TITLE
Just updated, crashed

### ISSUE THREAD

**Issue by zc1108aaa** [fzzyhmstrs/EMI_loot#72]
[crash-2024-09-01_01.36.33-client.txt](https://github.com/user-attachments/files/16825537/crash-2024-09-01_01.36.33-client.txt)
0
[latest.log](https://github.com/user-attachments/files/16825539/latest.log)

**Comment by unilock** [comment]
Install Fzzy Config: https://modrinth.com/mod/fzzy-config

@fzzyhmstrs Maybe this should be added to the fabric.mod.json?

**Comment by fzzyhmstrs** [comment]
You are right, it should.

**Comment by zc1108aaa** [comment]
Pre installed, no prompt for update
Later on, there was no mention of a pre mod
Many mods have this issue
Both mods have this issue
Otherwise, there wouldn't have been this mistake
