### ISSUE TITLE
[Suggestion] LootJS compatibility

### ISSUE THREAD

**Issue by Cicopath** [fzzyhmstrs/EMI_loot#74]
At the moment, in Fabric 1.20.1, loot added by LootLS loot modifiers are not displayed by EMI Loot. It'd be greatly beneficial for both modpack developers and players of modpacks utilizing LootJS if these mods were compatible with each other!

**Comment by fzzyhmstrs** [comment]
Unfortunately LootJS works by modifying drops at generation time, instead of modifying loot tables directly; so EMI Loot has no way of seeing the modifications or knowing what they are or will be.
