### ISSUE TITLE
Add cat gifts

### ISSUE THREAD

**Issue by Abbie5** [fzzyhmstrs/EMI_loot#8]
Tamed cats can give players gifts when they wake up. This provides a peaceful way of obtaining phantom membrane, for example.
More details: https://minecraft.fandom.com/wiki/Cat#Gifts

**Comment by fzzyhmstrs** [comment]
this is planned! Gameplay Loot (fishing, village hero gifts, cat gifts, etc) will probably make it into 0.6.0 or 0.7.0

**Comment by fzzyhmstrs** [comment]
This is added as of 0.6.0
