### ISSUE TITLE
neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [fzzyhmstrs/EMI_loot#85]
![image](https://github.com/user-attachments/assets/b533e715-9500-45b8-a426-33a41cb65424)

**Comment by fzzyhmstrs** [comment]
Can you send me the log game log please

**Comment by VaporeonScripts** [comment]
yes

**Comment by VaporeonScripts** [comment]
one second

**Comment by VaporeonScripts** [comment]
https://mclo.gs/chx0haq

**Comment by VaporeonScripts** [comment]
ima see rn

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/e5bf4726-41f4-4436-9313-de6c1aa03870)
same shit

**Comment by VaporeonScripts** [comment]
the mod must be not adapted for mod menu mod or idk

**Comment by fzzyhmstrs** [comment]
Well skinLayers3d is a totally different mod. I have no idea why their config wouldn't be working, but it's not EMI Loot, which is what I'm curious about.

**Comment by VaporeonScripts** [comment]
oh lmfao, my bad i forgot which thread i were, anyways same error as first pic, again,  my bad :sob:

**Comment by VaporeonScripts** [comment]
wait no, with visual overhaul removed the config works

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/1266b66c-ebd9-45c4-b147-0ab06e416eb8)

**Comment by fzzyhmstrs** [comment]
Thank you for confirming. I've opened an issue with Visual Overhaul, hopefully they can fix the compatibility issue soon.

**Comment by VaporeonScripts** [comment]
Alright,ty

**Comment by fzzyhmstrs** [comment]
Closing this. As of Fzzy Config 0.5.0, the issue should be dodged from FC's side, as it no longer uses the widget that was causing the problems.

**Comment by VaporeonScripts** [comment]
alright
