### ISSUE TITLE
[Feature Request] Display loot-references

### ISSUE THREAD

**Issue by Disketaa** [fzzyhmstrs/EMI_loot#89]
I'm using this structure:

Zombie loottable
> can roll rotten flesh
> can roll iron loottable

Iron loottable
> can roll iron ingot
> can roll iron nugget

But iron doesn't show up in EMI Loot screen.
Am I doing something wrong?

**Comment by fzzyhmstrs** [comment]
EMI Loot does display loot table entries. What type did you give the "Iron" loot table? e.g. "minecraft:chest", "minecraft:entity", etc. Or did you not give a type?

**Comment by Disketaa** [comment]
Yeah, "chest" type works fine, thanks

**Comment by fzzyhmstrs** [comment]
I would recommend using entity type if it is for an entity drop
