### ISSUE TITLE
[Feature Request] Ability to sort recipes / categories

### ISSUE THREAD

**Issue by Disketaa** [fzzyhmstrs/EMI_loot#91]
May I ask you to add .json configuration in somewhere in assets/emi_loot? Or maybe it's possible to do already, I don't know.

If not, maybe some .json in assets folder similar to this:
```
{
 [
  "gameplay/fishing/fish",
  "gameplay/fishing/treasure"
 ]
}
```
(undocumented recipes will move at the bottom of the list)

And then "treasure" loottable will be below fish loottable
![image](https://github.com/user-attachments/assets/92b0d539-3dd2-4334-a658-39a20fa07020)

**Comment by fzzyhmstrs** [comment]
I believe this is a possible future feature for EMI itself. I don't plan on special support just for EL categories. Otherwise, this is still better as a feature request for base EMI.
