### ISSUE TITLE
[Feature Request] Text color might match to EMI's one

### ISSUE THREAD

**Issue by Disketaa** [fzzyhmstrs/EMI_loot#92]
(changing gray text color into white with shadow)

This EMI's coloring:
![image](https://github.com/user-attachments/assets/c093e702-81e9-4071-be0c-e086f5a42ab5)

This is EMI Loot's coloring:
![image](https://github.com/user-attachments/assets/9e0bf9ec-4de2-4977-9520-2cfd9ede0515)

This is the match:
![image](https://github.com/user-attachments/assets/fb5844ba-cfa2-4b9a-bc8b-c265e3cc668a)

**Comment by fzzyhmstrs** [comment]
EMIs coloring is much harder to read. I won't be matching
